빌지 구현
billmanager, finished table 수정중
NullReferenceException: Object reference not set to an instance of an object
SerializedObjectNotCreatableException: Object at index 0 is null
ArgumentNullException: Value cannot be null.
Parameter name: componentOrGameObject
오류발견했는데 위 스크립트 수정으로 인한 오류인지는 모르겠음 동작은 잘됨.